### PR TITLE
Complete meetup: claim rewards and test balances

### PR DESCRIPTION
**Pull request by echevrier**
- Add balances getter and trusted calls. 
- Update the demo to complete a meetup for a private community (add missing claim_rewards) The participants get rewards in community currency and have some balances.
- Add some documentation on the demo in the Readme
-> Problem: the demurrage is not working. See https://github.com/encointer/community-sidechain/issues/50

### CODE REVIEW

**Comment by echevrier** [comment]
Perform meetup is available : https://github.com/encointer/community-sidechain/pull/39

**Review by brenzi — COMMENTED** [review]
When I check the CI logs, the claim seems to have failed: 
Bob has zero balance after a performed and claimed gathering. Why is that? Is this different when running locally?
```
encointer-private-community-demo  | Check Bob balances
encointer-private-community-demo  | Initial balances
encointer-private-community-demo  |   in native currency: 0
encointer-private-community-demo  |   in community currency: 0
encointer-private-community-demo  | After rewards
encointer-private-community-demo  |   in native currency: 0
encointer-private-community-demo  |   in community currency: 0
encointer-private-community-demo  | 
encointer-private-community-demo  | After some time (demurrage)
encointer-private-community-demo  |   in native currency: 0
encointer-private-community-demo  |   in community currency: 0
encointer-private-community-demo  | 
```

**Comment by echevrier** [comment]
> When I check the [CI logs](https://github.com/encointer/community-sidechain/actions/runs/4609512223/jobs/8160421654#step:7:421), the claim seems to have failed: Bob has zero balance after a performed and claimed gathering. Why is that? Is this different when running locally?
> 
> ```
> encointer-private-community-demo  | Check Bob balances
> encointer-private-community-demo  | Initial balances
> encointer-private-community-demo  |   in native currency: 0
> encointer-private-community-demo  |   in community currency: 0
> encointer-private-community-demo  | After rewards
> encointer-private-community-demo  |   in native currency: 0
> encointer-private-community-demo  |   in community currency: 0
> encointer-private-community-demo  | 
> encointer-private-community-demo  | After some time (demurrage)
> encointer-private-community-demo  |   in native currency: 0
> encointer-private-community-demo  |   in community currency: 0
> encointer-private-community-demo  | 
> ```
One bootstrapper couldn't register:
```
* Registering participants : 
- Registering 3 bootstrappers : 
  //Alice,
  //Bob
  //Charlie
- Registering a newbie //Cora 

* Listing participants 
Participants of community sqm1v79dF6b for ceremony 2 :
- Bootstrappers :
    5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty
    5FLSigC9HGRKVhB9FiEo4Y3koPsNmBmLJbpXg2mp1hXcS59Y

- Reputables :
    No one

- Endorsees :
    No one

- Newbies :
    5DDZ8VeTs9ny15fKuuY99iByF4uGN5n953ZC64dUjyCBiCG5
```
 
Maybe because of  the bad performance of the GitHub actions CI. Something like https://github.com/integritee-network/worker/issues/1132

In the worker logs, we have:
```
[2023-04-04T16:28:25Z WARN  its_consensus_common::block_import] Could not peek parentchain block, returning latest parentchain block (Other("Failed to find parentchain header in import queue (hash: 0x968e…1fc7) that is associated with the current sidechain block that is to be imported (number: 12, hash: 0xd50c…88c3)"))
[2023-04-04T16:28:25Z ERROR its_block_verification] Author verification for block (number: 12) failed, block will be discarded
[2023-04-04T16:28:25Z ERROR enclave_runtime::error] Returning error Consensus(VerificationError(BadParentchainBlock(0x38a1627e5bc3507c0ad9c0b4abbf5aa9cb8af81eaaf927057a6b496504bd24d9, "Invalid parentchain head"))) as sgx unexpected.
[2023-04-04T16:28:25Z ERROR integritee_service::sidechain_setup] Sgx(SGX_ERROR_UNEXPECTED)
...
```
1 bootstrapper was not registered:
```
[2023-04-04T16:34:12Z ERROR itp_stf_executor::executor] Stf execute failed: Dispatch("Ceremonies attendees attestation error: Module(ModuleError { index: 61, error: [19, 0, 0, 0], message: Some(\"ParticipantIsNotRegistered\") })")
[2023-04-04T16:34:12Z WARN  its_consensus_slots::slots] Proposed block slot time: 1680626052958 ms, slot start: 1680626052600 ms , slot end: 1680626052900 ms
[2023-04-04T16:34:12Z WARN  aura] ⌛️ Discarding proposal for slot 5602086842, block number 333; block production took too long
[2023-04-04T16:34:13Z WARN  its_consensus_common::peer_block_sync] Got ancestry mismatch error upon block import. Attempting to fetch missing blocks from peer
```
The attestaions failed:
```
[2023-04-04T16:34:32Z ERROR itp_stf_executor::executor] Stf execute failed: Dispatch("Ceremonies attendees attestation error: Module(ModuleError { index: 61, error: [15, 0, 0, 0], message: Some(\"TooManyAttestations\") })")
Syncing Parentchain block number 66 at Sidechain block number  339 
[2023-04-04T16:34:32Z WARN  its_consensus_common::peer_block_sync] Got ancestry mismatch error upon block import. Attempting to fetch missing blocks from peer
[2023-04-04T16:34:33Z ERROR enclave_runtime::error] Returning error Consensus(BlockAncestryMismatch(339, 0x6b962c11585b218cfa039c223607f7bec87d862a99949a1cf24a9b4d6f386508, "Invalid block number, 652 does not succeed 339")) as sgx unexpected.
[2023-04-04T16:34:33Z ERROR integritee_service::sidechain_setup] Sgx(SGX_ERROR_UNEXPECTED)
```
The claim rewards failed:

```
[2023-04-04T16:36:16Z ERROR itp_stf_executor::executor] Stf execute failed: Dispatch("Ceremonies claim rewards error: Module(ModuleError { index: 61, error: [23, 0, 0, 0], message: Some(\"VotesNotDependable\") })")
[2023-04-04T16:36:16Z WARN  its_consensus_slots::slots] Proposed block slot time: 1680626176358 ms, slot start: 1680626175879 ms , slot end: 1680626175900 ms
[2023-04-04T16:36:16Z WARN  aura] ⌛️ Discarding proposal for slot 5602087252, block number 386; block production took too long
[2023-04-04T16:36:16Z WARN  its_consensus_common::peer_block_sync] Got ancestry mismatch error upon block import. Attempting to fetch missing blocks from peer
[2023-04-04T16:36:16Z ERROR enclave_runtime::error] Returning error Consensus(BlockAncestryMismatch(385, 0x4cfcfba0b01973eba096cfa9f189c7dfd91c21e1c65062aab677617f29057219, "Invalid block number, 802 does not succeed 385")) as sgx unexpected.
[2023-04-04T16:36:16Z ERROR integritee_service::sidechain_setup] Sgx(SGX_ERROR_UNEXPECTED)
```

**Comment by echevrier** [comment]
Re-running the demo. The demo ran successfully:
```
encointer-private-community-demo  | Check Bob balances
encointer-private-community-demo  | Initial balances
encointer-private-community-demo  |   in native currency: 0
encointer-private-community-demo  |   in community currency: 0
encointer-private-community-demo  | After rewards
encointer-private-community-demo  |   in native currency: 0
encointer-private-community-demo  |   in community currency: 999999211267759304
encointer-private-community-demo  | 
encointer-private-community-demo  | After some time (demurrage)
encointer-private-community-demo  |   in native currency: 0
encointer-private-community-demo  |   in community currency: 999998647887968255
```

**Review by brenzi — APPROVED** [review]
let's see if CI is really brittle in the future. acceptable for now, thx

**Pull request merged**
